json.extract! gym,
                  :id,
                  :name,
                  :address,
                  :city,
                  :state,
                  :zip,
                  :level,
                  :price,
                  :hours,
                  :phone,
                  :lat,
                  :lng,
                  :website_url,
                  :image_url
json.reviews gym.reviews
